### DISCUSSION TITLE
Issue with Hoop Agent Connection in k8s Deployment

### DISCUSSION THREAD

**Discussion by femiadewale780** [hoophq/hoop#529] [Q&A] [answered]
Hi team,
I've deployed `hoop-gateway` and `hoop-agent` using the Helm chart via ArgoCD on Kubernetes. The gateway is functioning correctly, but I’m having trouble with the agent’s connection.

I generated a `HOOP_KEY` by running the following
```
hoop config create --api-url=https://hoop.example.com
hoop login
hoop admin create agent app-dev
```
```
hoop admin get agents
NAME      MODE    VERSION  HOSTNAME  PLATFORM  STATUS
app-dev  standard  -     -     -               OFFLINE
```
The key generated was then used to configure the agent

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hoop-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: all-clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/example/dev.git
    targetRevision: helm.hoop-agent-20241030T194707
    path: helm/hoop-agent
    helm:
      releaseName: hoop-agent
      values: |
        secrets:
          path: hoop-agent/agent
        image:
          repository: hoophq/hoopdev
          pullPolicy: Always
          tag: 1.27.6
        config:
          HOOP_KEY:
            secretRef: hoop-agent
            secretKey: HOOP_KEY
          LOG_LEVEL: 'debug'
          LOG_ENCODING: 'json'
  destination:
    name: dev
    namespace: hoop-dev
```
#### Logs from the Agent Pod

```
{"level":"warn","timestamp":"2024-10-31T15:20:33Z","logger":"agent/main.go:175","msg":"failed to connect to 127.0.0.1:8010, reason=failed connecting to streaming RPC server, err=rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:8010: connect: connection refused\"","version":"1.27.6","backoff":"4m16s"}
{"level":"info","timestamp":"2024-10-31T15:24:49Z","logger":"agent/main.go:171","msg":"connecting to 127.0.0.1:8010, tls=false","version":"1.27.6","backoff":"4m16s"}
```

When I try from the command line
```
% export HOOP_KEY=grpc://app-dev:*******@127.0.0.1:8010?mode=standard
% hoop start agent
{"level":"info","timestamp":"2024-10-31T11:08:40-05:00","logger":"agent/main.go:166","msg":"version=1.27.7, platform=darwin/arm64, type=dsn, mode=standard, grpc_server=127.0.0.1:8010, tls=false, tlsca=false - starting agent"}
{"level":"info","timestamp":"2024-10-31T11:08:40-05:00","logger":"agent/main.go:171","msg":"connecting to 127.0.0.1:8010, tls=false","version":"1.27.7","backoff":"1s"}
{"level":"warn","timestamp":"2024-10-31T11:08:40-05:00","logger":"agent/main.go:175","msg":"failed to connect to 127.0.0.1:8010, reason=failed connecting to streaming RPC server, err=rpc error: code = Unavailable desc = connection error: desc
= \"transport: Error while dialing: dial tcp 127.0.0.1:8010: connect: connection refused\"","version":"1.27.7","backoff":"1s"}

```
The web app seems not to work either 
<img width="161" alt="Screenshot 2024-10-31 at 12 34 25 PM" src="https://github.com/user-attachments/assets/5af4d5a8-9f17-4d7a-8b8d-e2c664dcbe4c">

Any guidance on resolving this connection issue would be greatly appreciated!
