### ISSUE TITLE
ARM64 / Rasberry Pi 5 image for Hoop?

### ISSUE THREAD

**Issue by RFlintstone** [hoophq/hoop#422]
Hello everyone at Hoop!
I'm very much interested in running this on my Rasberry Pi 5 based cluster and I was wondering if there is an image to run Hoop on a Kubernetes/K3S cluster. The image currently pulls off because it is build for the amd architecture and apparently I couldn't build my own because of 'checkout libhoop' being a private repo (or, at least, I couldn't find it).
I'd like to hear if it is possible as I'm looking for a secure way to access my databases and SSH along with a few other features you are offering. 🙂

**Comment by sandromello** [comment]
Hey Ruben, we still lack any official Docker image for this architecture. However we have builds for this architecture where you could install and build in your own image. Here's an example using our one line shell installer:

```Dockerfile
FROM python:3.9-slim
RUN mkdir /app
WORKDIR /app
RUN apt-get update -y && \
    apt-get install curl -y && \
    curl -s -L https://releases.hoop.dev/release/install-cli.sh | sh
```

**Comment by RFlintstone** [comment]
> Hey Ruben, we still lack any official Docker image for this architecture. However we have builds for this architecture where you could install and build in your own image. Here's an example using our one line shell installer:
> 
> ```dockerfile
> FROM python:3.9-slim
> RUN mkdir /app
> WORKDIR /app
> RUN apt-get update -y && \
>     apt-get install curl -y && \
>     curl -s -L https://releases.hoop.dev/release/install-cli.sh | sh
> ```

Hello Sandro, thank you for the info and snippet!
Ah, alright. I thought there could be something I overlooked given the release workflow you use ([L215](https://github.com/hoophq/hoop/blob/main/.github/workflows/release.yml#L215)).
The build is ok but I think the CLI wont play nice as when I execute 'hoop login' as mentioned by the [documentation](https://hoop.dev/docs/getting-started/cli) page I'm getting this error:
```
root@6fb27a70a589:/app# hoop login
failed decoding response body, err=json: cannot unmarshal number into Go value of type cmd.login
```

**Comment by sandromello** [comment]
If your goal is connecting your Kubernetes cluster to Hoop, you need to deploy only agents in your cluster. This component is run by issuing the command:

```shell
export HOOP_KEY=
hoop start agent
```

Then you use `hoop login` in your **local machine** to authenticate in the api to generate an agent key:

```shell
# configure
hoop config create --api-url https://your-hoop-gateway
# login
hoop login
# create HOOP_KEY
hoop admin create agent testagent
```

The `HOOP_KEY` is used to connect the agent to the gateway

**Comment by RFlintstone** [comment]
> If your goal is connecting your Kubernetes cluster to Hoop, you need to deploy only agents in your cluster. This component is run by the following subcommand:
> 
> ```shell
> export HOOP_KEY=
> hoop start agent
> ```
> 
> Then you use `hoop login` in your **local machine** to authenticate in the api to generate an agent key:
> 
> ```shell
> # configure
> hoop config create --api-url https://your-hoop-gateway
> # login
> hoop login
> # create the HOOP_KEY
> hoop admin create agent testagent
> ```
> 
> The output of the last command is your `HOOP_KEY`

This works for me as a temporary solution:

Dockerfile:
```yaml
FROM python:3.9-slim

# Create and set the working directory
RUN mkdir /app
WORKDIR /app

# Install necessary packages and hoop agent
RUN apt-get update -y && \
    apt-get install -y curl bash && \
    curl -s -L https://releases.hoop.dev/release/install-cli.sh | sh

# Install kubectl for ARM64 architecture
RUN curl -sL "https://dl.k8s.io/release/v1.22.1/bin/linux/arm64/kubectl" -o /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

# Create the .kube directory and copy the k3s.yaml file
COPY config/k3s.yaml /tmp/kubeconfig

# Set the KUBECONFIG environment variable
ENV KUBECONFIG=/root/.kube/config

# Set the correct permissions for the kubeconfig file
RUN chmod 600 /tmp/kubeconfig

# Copy the .env file into the container
COPY .env .env

# Set the HOOP_KEY environment variable
ARG HOOP_KEY
ENV HOOP_KEY=${HOOP_KEY}

# Start the hoop agent using command syntax, sourcing the .env file first
CMD ["bash", "-c", "source .env && hoop start agent"]
```

.env
```yaml
HOOP_KEY=
```

and run:
```yaml
mkdir config
cp /etc/rancher/k3s/k3s.yaml ./config
docker build -t hoop .
docker run -it hoop
```

This connects to hoop and preinstalls kubectl too, so you can manage a kubernetes cluster.
Whenever the official arm64 image is published I'll most likely switch. 

Note that I didn't try it as a deployment on kubenetes yet but it should work all the same.

**Comment by sandromello** [comment]
Nice! Just an observation about the `.env` file. Be careful on publishing this image to any registry because it will contain the agent key which is a sensitive secret. If you're deploying on Kubernetes you could use secrets resources and expose them as environment variables.

**Comment by RFlintstone** [comment]
> Nice! Just an observation about the `.env` file. Be careful on publishing this image to any registry because it will contain the agent key which is a sensitive secret. If you're deploying on Kubernetes you could use secrets resources and expose them as environment variables.

Thanks for the suggestion. I just finished it!
This works without exposing the ENV using the image.

```dockerfile
FROM python:3.9-slim

# Create and set the working directory
RUN mkdir /app
WORKDIR /app

# Install necessary packages and hoop agent
RUN apt-get update -y && \
    apt-get install -y curl bash && \
    curl -s -L https://releases.hoop.dev/release/install-cli.sh | sh

# Install kubectl for ARM64 architecture
RUN curl -sL "https://dl.k8s.io/release/v1.22.1/bin/linux/arm64/kubectl" -o /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

# Start the hoop agent using command syntax
CMD ["bash", "-c", "hoop start agent"]
```
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoop-agent
  namespace: hoopdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoop-agent
  template:
    metadata:
      labels:
        app: hoop-agent
    spec:
      containers:
      - name: hoop-agent
        image: user/hoop:latest
        env:
        - name: HOOP_KEY
          valueFrom:
            secretKeyRef:
              name: hoop-secret
              key: HOOP_KEY
        - name: KUBECONFIG 
          value: /tmp/kubeconfig
        volumeMounts:
        - name: kubeconfig
          mountPath: /tmp/kubeconfig
          subPath: kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret # 
          items:
            - key: kubeconfig
              path: kubeconfig
      imagePullSecrets:
      - name: regcred
```
```yaml
# note: I tested key as a base64 but that will give a wrong format error. 
kubectl create secret generic hoop-secret \
  --from-literal=HOOP_KEY=key \
  -n hoopdev
```
```yaml
# note: change from-file depending on where the kubeconfig file is located
kubectl create secret generic kubeconfig-secret --from-file=kubeconfig=/etc/rancher/k3s/k3s.yaml -n hoopdev --dry-run=client -o yaml | kubectl apply -f -
```

How to pull from a private docker registry: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

when done you can just apply the deployment
