### ISSUE TITLE
Feature request: additional containers in helm chart

### ISSUE THREAD

**Issue by johnjelinek** [hoophq/hoop#784]
I'd like to be able to spin up a sidecar cloud-sql-proxy container that hoop can connect to. Can you please add a value for additional containers? Example container:
```
- name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
      args:
        - --auto-iam-authn
```
☝ will allow me to wire up passwordless auth to the hoop postgres DB with an IAM google service account.
